### PR TITLE
Tallying of votes

### LINKED ISSUE #18: [Blockchain] Upon request, votes should be tallied by decrypting them
- [ ] Each vote is decrypted
- [ ] Candidate/party/blank has vote count incremented

### PR DESCRIPTION
**Pull request by Jatewo**
## Description
This pull request includes several changes to improve the functionality and security of the election system. The most important changes include adding environment variable configuration, updating the vote and tallying processes, and enhancing the test coverage.

### Environment Configuration

* [`config/keys.js`](diffhunk://#diff-79d33c4fac1e062c80d68384f4edd2c2c915c1dae388658f63f02f3f34149f09R1-R20): Added environment variable configuration using `dotenv` to load environment variables based on `NODE_ENV` and export them for use in the application.

### Vote and Tallying Processes

* [`controllers/tallying.js`](diffhunk://#diff-5b465313a007982b1b437b36c046d63c72f491d10c9aeccd69e14978f059254bR1-R75): Implemented the `decryptAndTallyVotes` function to decrypt votes and tally them using the Paillier cryptosystem.
* [`controllers/vote.js`](diffhunk://#diff-23dbd3aeaf878b223d47ce6b8b35e4fe3d064c0185095e1be2ea8cb6b4cd4f9bL4-R12): Updated the `vote` function to use the Paillier cryptosystem for encrypting votes and handling the encryption key. [[1]](diffhunk://#diff-23dbd3aeaf878b223d47ce6b8b35e4fe3d064c0185095e1be2ea8cb6b4cd4f9bL4-R12) [[2]](diffhunk://#diff-23dbd3aeaf878b223d47ce6b8b35e4fe3d064c0185095e1be2ea8cb6b4cd4f9bL25-R57)

### Middleware and Authentication

* [`middleware/auth.js`](diffhunk://#diff-e135f48acbdd2de273a36dcabccdbe0da897b962814b48b60aa1ea8af86034d8R3): Modified the `auth` middleware to use the JWT secret from the new `keys` configuration file instead of directly from environment variables. [[1]](diffhunk://#diff-e135f48acbdd2de273a36dcabccdbe0da897b962814b48b60aa1ea8af86034d8R3) [[2]](diffhunk://#diff-e135f48acbdd2de273a36dcabccdbe0da897b962814b48b60aa1ea8af86034d8L16-R17)

### Test Enhancements

* [`test/middleware/auth.test.js`](diffhunk://#diff-ec7c9e8435be7c486eac7ee791c1b245ad9260d7b2a2b8e36805f2cf76391a51L1-R17): Updated the tests to mock the JWT secret from the new `keys` configuration file and added additional test cases for the `auth` middleware. [[1]](diffhunk://#diff-ec7c9e8435be7c486eac7ee791c1b245ad9260d7b2a2b8e36805f2cf76391a51L1-R17) [[2]](diffhunk://#diff-ec7c9e8435be7c486eac7ee791c1b245ad9260d7b2a2b8e36805f2cf76391a51R46-R53)
* [`test/routes/tallyRoutes.test.js`](diffhunk://#diff-a6ffa3826f2e05fa1bdff0f1d1768ae16bceffcb34ff8665f4b887bbe0fbba87L6-R17): Added tests for the new tallying endpoint to ensure it handles different election phases and returns correct results. [[1]](diffhunk://#diff-a6ffa3826f2e05fa1bdff0f1d1768ae16bceffcb34ff8665f4b887bbe0fbba87L6-R17) [[2]](diffhunk://#diff-a6ffa3826f2e05fa1bdff0f1d1768ae16bceffcb34ff8665f4b887bbe0fbba87R111-R195)

### Dependencies

* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R22-R43): Added the `paillier-bigint` library for cryptographic operations and updated other dependencies to the latest versions.

### CODE REVIEW

**Review by TheMOHD3886 — DISMISSED** [review]
lgtm dawg 👍

**Review by Fantaskink — APPROVED** [review]
lgtm dawg

**Review by Mafusn — APPROVED** [review]
LGTM 🧶

**Review by TheMOHD3886 — APPROVED** [review]
still lgtm 👍

**Pull request merged**
